# @package _global_
robot:
  follower_port: /dev/tty.usbmodem5A680099311
  leader_port:   /dev/tty.usbmodem5A680094911
  cam_index: 0
  cam_width: 640
  cam_height: 480
  fps: 30
  cam2_index: 2
  cam2_width: 1280
  cam2_height: 720